### ISSUE TITLE
Can't do new maps

### ISSUE THREAD

**Issue by Apoxied** [WinterSquire/BlamScript#1]
I edited these lines to reflect the new map I'm trying to edit. Once I click "run", the scenario file isn't being edited.

var src = TagPath.FromPathAndType(@"levels\campaign_jv\030_outskirts\030_outskirts_part1_jv"

var dst = TagPath.FromPathAndType(@"mod\030_outskirts_part1_jv_new", "scnr");

var scnr_tag_path = TagPath.FromPathAndType(@"mod\030_outskirts_part1_jv_new", "scnr");

**Comment by WinterSquire** [comment]
You have to make your [choice](https://github.com/WinterSquire/BlamScript/blob/master/H3/Program.cs#L17) for using which function.

**Comment by Apoxied** [comment]
> You have to make your [choice](https://github.com/WinterSquire/BlamScript/blob/master/H3/Program.cs#L17) for using which function.

I changed the value of my choice to "0", and this is the error I received.

Unhandled Exception: Bungie.Tags.TagLoadException: Tag file does not exist
at Bungie.Tags.TagFile.Load(TagPath tagPath, Boolean isWeak)
at Bungie.Tags.TagFile..ctor(TagPath tagPath)
at H3.Program.BlamTask1(TagPath src, TagPath dst, Int64 maximum_allowed, Single price_per_instance) in C:\Users\ClearlyMe\Documents\C#\BlamScript\H3\Program.cs:line 89
at H3.Program.Main(String[] args) in C:\Users\ClearlyMe\Documents\C#\BlamScript\H3\Program.cs:line 28
Press any key to continue . . .

**Comment by WinterSquire** [comment]
As it said `the Tag file does not exist`.
Is the `h3ek` directory correct? Is the tag path valid? Does your tag exist?

**Comment by Apoxied** [comment]
Directory is correct.

path to the scenario I want to grab from:
"E:\Steam\steamapps\common\H3EK\tags\levels\campaign_jv\030_outskirts\030_outskirts_part1_jv.scenario"

path I want the objects sent to:
"E:\Steam\steamapps\common\H3EK\tags\levels\campaign_jv\030_outskirts\030_outskirts_part1_jv_new.scenario"



I tried seeing if it was maybe because I'm editing scenarios within the same folder, by using the normal campaign map from the solo levels folder. But that didn't work either. No matter what files I specify, it says it doesn't exist.

**Comment by WinterSquire** [comment]
TagPath supports these functions to locate tag files.
```
TagPath FromTagReference(s_tag_reference* reference);
TagPath FromFilename(string filename_full_path);
TagPath FromPathAndType(string tagPath, string type);
TagPath FromPathAndExtension(string tagPath, string extension);
```
I suggest you to try `FromFilename` function.
